### ISSUE TITLE
Walking for water forever

### ISSUE THREAD

**Issue by TheBlueBurger** [adrisj7-AltoClef/altoclef#43] opened 2021-06-02 15:04 UTC
https://youtu.be/_kb0x-szNso
Time: 42:30

**Comment by TheBlueBurger** [comment] 2021-06-02 15:05
Edit: it got water, but it took over 5 minutes

**Comment by adrisj7** [comment] 2021-06-02 16:13
Duplicate of https://github.com/adrisj7-AltoClef/altoclef/issues/33, will close this one but add the video since that might be a good example.

**Closed by adrisj7** 2021-06-02 16:13 UTC
